### ISSUE TITLE
Ghost 2.0 Announcement for Theme Developers

### ISSUE THREAD

**Issue by JohnONolan** [TryGhost/Marketplace#84]
Hey everyone! Sorry about the mass notification: **We’ll be releasing Ghost 2.0 at the end of August** 🎉 This means shipping the final version of our [new editor](https://forum.ghost.org/t/koenig-editor-beta-release/1284) ([docs](https://themes.ghost.org/v2.0.0/docs/ghost-editor)), as well as introducing powerful new [dynamic routing](https://docs.ghost.org/v2/docs/dynamic-routing). 

For developers publishing Ghost themes, it’s important to note that there will be some small breaking changes, since new editor has slightly different output on the front-end.

Existing themes will work with 2.0 but there are some new features which will not work, such as displaying full-width images in posts. Consider this a pre-launch warning to ensure that your themes are compatible with all new features in Ghost 2.0 👻

<br>

### Update your theme to be 2.0 compatible

We’ve updated gscan to test compatibility for Ghost 2.0 and update your themes accordingly. 

<h3><a href="https://gscan.ghost.org">➡️ Test your theme now</a></h3>

<br><br>

# Subscribe to future updates

At the moment there’s no easy way of reaching out to theme developers to let them know about important changes happening in Ghost - hence this rather convoluted Github issue. If you’d like us to drop a note in your inbox for future breaking changes, make sure you drop your email address in the subscribe box on [gscan.ghost.org
](https://gscan.ghost.org)
We’ll only ever email you once or twice a year when applicable. No spam, no cross-promotion, no jibber jabber. Unsubscribe any time.

----------

/cc

@zutrinken @mityalebedev @OlivierNguyen @oswaldoacauan @roryg @Kikobeats @mbejda @h4t0n @juan-g @curiositry @sethlilly @kathyqian @wbkd @grmmph @kelyvin @godofredoninja @jrdnbwmn @fueko @NistorCristian @TomasBankauskas @ahmadajmi @norberthunyadi @minimaluminium @simtun @biswajit-saha @cadoo @messaworks @javierencalada @themeix @nitinthewiz @rosario @onevcat @foru17 @damianmuti @GavickPro @dongri @xiaoluoboding @nauzethc @roycehaynes

**Comment by damianmuti** [comment]
Thanks for the heads up, John. 👍

**Comment by biswajit-saha** [comment]
Thank you john for letting us know. It will be really helpful. Specially the new documentation will be very helpful :)
I have a question?
Just tested a theme by adding `.kg-width-wide` and `.kg-width-full` class between a `<style>` tag under `<head>` tag of `default.hbs` file.

Gscan can't detect that. But when I added those class in a CSS file then Gscan error gone. Is it intended behavior?

**Comment by kirrg001** [comment]
@biswajit-saha 

> Just tested a theme by adding .kg-width-wide and .kg-width-full class between a <style> tag under <head> tag of default.hbs file.

GScan should detect that. Thanks for reporting 👍

**Comment by themeix** [comment]
Thats great, waiting for the stable version of 2.0

**Comment by Rohitkrops** [comment]
Awesome update, loving the Keonig editor. I just updated my theme Paper (http://bit.ly/2NQyL9s) to support it.

**Comment by curiositry** [comment]
Thanks for keeping us posted @JohnONolan! Great idea to have a theme developer mailing list. I was recently griping about the lack of an changelog RSS feed on the Ghost forum, but you went one better.

I have updated all my themes: **[Laminim](https://creativemarket.com/Curiositry/1037280-Laminim-%E2%80%94-Ghost-Theme-for-Bloggers)** *(premium)*, **[MNML](https://github.com/curiositry/mnml-ghost-theme)** *(open-source)*, and **[Undefined](https://github.com/curiositry/undefined-ghost-theme)** *(open-source, starter theme)*.
